apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-graph-svc.fullname" . }}
  labels:
    {{- include "mcp-graph-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "mcp-graph-svc.selectorLabels" . | nindent 4 }}

